# Generated by Django 3.1 on 2020-09-07 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.date(2020, 9, 7)),
        ),
        migrations.AlterField(
            model_name='user',
            name='signup',
            field=models.DateTimeField(default=datetime.date(2020, 9, 7)),
        ),
    ]
