# Generated by Django 3.1 on 2020-09-08 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.date(2020, 9, 8)),
        ),
        migrations.AlterField(
            model_name='user',
            name='signup',
            field=models.DateTimeField(default=datetime.date(2020, 9, 8)),
        ),
    ]
