# Generated by Django 3.1 on 2020-09-13 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20200908_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.date(2020, 9, 13)),
        ),
        migrations.AlterField(
            model_name='user',
            name='signup',
            field=models.DateTimeField(default=datetime.date(2020, 9, 13)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
